# docker-compose.yml
version: '1.0'

services:
    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DATABASE=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql